apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:catalogue-dev-stage
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/catalogue
    helm:
      valueFiles:
        - /env/dev/catalogue/catalogue-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true