apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendation-prod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: craftista:recommendation-prod-stage
spec:
  project: craftista
  source:
    repoURL: https://github.com/nitheeshp-irl/microservice-helmcharts
    targetRevision: main
    path: service-charts/recommendation
    helm:
      valueFiles:
        - /env/prod/recommendation/recommendation-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true