replicaCount: 1

image:
  repository: reyewkha/craftista-voting
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: "512Mi"
  requests:
    cpu: "100m"
    memory: "256Mi"